sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.5"

before_install:
  - pip3 install cwltool
  - docker build -t psuedofinder .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /psuedofinder/.travis/unit-test.sh psuedofinder
  # Unit tests
  - docker run --entrypoint /psuedofinder/functional_tests/psuedofinder-test.sh psuedofinder -p psuedofinder -d /psuedofinder/functional_tests/test_data -v

  # CWL definition test
  - cwltool psuedofinder.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
